### ISSUE TITLE
resiliency tests mock api throws 404 and all resiliency tests are not in scope of validation

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/cadl-ranch#75]
Hi @iscai-msft,
I saw this pr https://github.com/Azure/cadl-ranch/pull/73 renames resiliency tests name. But I found resiliency tests cadl files are updated, but mock api is not updated. It makes url path not consistent, so the mock api throws 404. Please refer to below code for the corresponding url path code.

What's more, resiliency tests are not included in validation. It should be included in validation.

cadl:
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/resiliency/srv-driven-1/main.cadl#L10

mockapi:
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/resiliency/srv-driven-1/mockapi.ts#L16

validation:
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch/src/actions/validate-mock-apis.ts#L86-L88

**Comment by iscai-msft** [comment]
thanks @haolingdong-msft . The resiliency tests have never worked which is why they're skipped in the validate mock api tests. I'm going to work on adding support for these by the end of the week so we can unskip them then. Thanks!

Closing in favor of this issue, since it already tracks the resiliency mock tests https://github.com/Azure/cadl-ranch/issues/41
